#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v20
# autospec commit: f35655a
#
Name     : qt6languageserver
Version  : 6.7.3
Release  : 21
URL      : https://download.qt.io/official_releases/qt/6.7/6.7.3/submodules/qtlanguageserver-everywhere-src-6.7.3.zip
Source0  : https://download.qt.io/official_releases/qt/6.7/6.7.3/submodules/qtlanguageserver-everywhere-src-6.7.3.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0 GPL-3.0 LGPL-3.0
Requires: qt6languageserver-lib = %{version}-%{release}
Requires: qt6languageserver-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : qt6base-dev
BuildRequires : qtbase-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package dev
Summary: dev components for the qt6languageserver package.
Group: Development
Requires: qt6languageserver-lib = %{version}-%{release}
Provides: qt6languageserver-devel = %{version}-%{release}
Requires: qt6languageserver = %{version}-%{release}

%description dev
dev components for the qt6languageserver package.


%package lib
Summary: lib components for the qt6languageserver package.
Group: Libraries
Requires: qt6languageserver-license = %{version}-%{release}

%description lib
lib components for the qt6languageserver package.


%package license
Summary: license components for the qt6languageserver package.
Group: Default

%description license
license components for the qt6languageserver package.


%prep
%setup -q -n qtlanguageserver-everywhere-src-6.7.3
cd %{_builddir}/qtlanguageserver-everywhere-src-6.7.3
pushd ..
cp -a qtlanguageserver-everywhere-src-6.7.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1727832318
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1727832318
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qt6languageserver
cp %{_builddir}/qtlanguageserver-everywhere-src-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/qt6languageserver/79453f55fa8ee32d7b95581473edcbfd043e088f || :
cp %{_builddir}/qtlanguageserver-everywhere-src-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/qt6languageserver/dc8f2e570bf431427dbc3bab9d4d551b53a60208 || :
cp %{_builddir}/qtlanguageserver-everywhere-src-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6languageserver/7713a1753ce88f2c7e6b054ecc8e4c786df76300 || :
cp %{_builddir}/qtlanguageserver-everywhere-src-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6languageserver/c70af14df11e3908dfc10397b1ba4b1f346661f3 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/QtJsonRpc/6.7.3/QtJsonRpc/private/qhttpmessagestreamparser_p.h
/usr/include/QtJsonRpc/6.7.3/QtJsonRpc/private/qjsonrpcprotocol_p.h
/usr/include/QtJsonRpc/6.7.3/QtJsonRpc/private/qjsonrpcprotocol_p_p.h
/usr/include/QtJsonRpc/6.7.3/QtJsonRpc/private/qjsonrpctransport_p.h
/usr/include/QtJsonRpc/6.7.3/QtJsonRpc/private/qjsontypedrpc_p.h
/usr/include/QtJsonRpc/6.7.3/QtJsonRpc/private/qtypedjson_p.h
/usr/include/QtJsonRpc/QtJsonRpc
/usr/include/QtJsonRpc/QtJsonRpcDepends
/usr/include/QtJsonRpc/QtJsonRpcVersion
/usr/include/QtJsonRpc/qtjsonrpcglobal.h
/usr/include/QtJsonRpc/qtjsonrpcversion.h
/usr/include/QtLanguageServer/6.7.3/QtLanguageServer/private/qlanguageserverbase_p.h
/usr/include/QtLanguageServer/6.7.3/QtLanguageServer/private/qlanguageserverbase_p_p.h
/usr/include/QtLanguageServer/6.7.3/QtLanguageServer/private/qlanguageservergen_p.h
/usr/include/QtLanguageServer/6.7.3/QtLanguageServer/private/qlanguageservergen_p_p.h
/usr/include/QtLanguageServer/6.7.3/QtLanguageServer/private/qlanguageserverjsonrpctransport_p.h
/usr/include/QtLanguageServer/6.7.3/QtLanguageServer/private/qlanguageserverprespectypes_p.h
/usr/include/QtLanguageServer/6.7.3/QtLanguageServer/private/qlanguageserverprotocol_p.h
/usr/include/QtLanguageServer/6.7.3/QtLanguageServer/private/qlanguageserverspec_p.h
/usr/include/QtLanguageServer/6.7.3/QtLanguageServer/private/qlanguageserverspectypes_p.h
/usr/include/QtLanguageServer/6.7.3/QtLanguageServer/private/qlspnotifysignals_p.h
/usr/include/QtLanguageServer/QtLanguageServer
/usr/include/QtLanguageServer/QtLanguageServerDepends
/usr/include/QtLanguageServer/QtLanguageServerVersion
/usr/include/QtLanguageServer/qtlanguageserverglobal.h
/usr/include/QtLanguageServer/qtlanguageserverversion.h
/usr/lib64/cmake/Qt6BuildInternals/StandaloneTests/QtLanguageServerTestsConfig.cmake
/usr/lib64/cmake/Qt6JsonRpcPrivate/Qt6JsonRpcPrivateAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6JsonRpcPrivate/Qt6JsonRpcPrivateConfig.cmake
/usr/lib64/cmake/Qt6JsonRpcPrivate/Qt6JsonRpcPrivateConfigVersion.cmake
/usr/lib64/cmake/Qt6JsonRpcPrivate/Qt6JsonRpcPrivateConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6JsonRpcPrivate/Qt6JsonRpcPrivateDependencies.cmake
/usr/lib64/cmake/Qt6JsonRpcPrivate/Qt6JsonRpcPrivateTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6JsonRpcPrivate/Qt6JsonRpcPrivateTargets.cmake
/usr/lib64/cmake/Qt6JsonRpcPrivate/Qt6JsonRpcPrivateVersionlessTargets.cmake
/usr/lib64/cmake/Qt6LanguageServerPrivate/Qt6LanguageServerPrivateAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6LanguageServerPrivate/Qt6LanguageServerPrivateConfig.cmake
/usr/lib64/cmake/Qt6LanguageServerPrivate/Qt6LanguageServerPrivateConfigVersion.cmake
/usr/lib64/cmake/Qt6LanguageServerPrivate/Qt6LanguageServerPrivateConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6LanguageServerPrivate/Qt6LanguageServerPrivateDependencies.cmake
/usr/lib64/cmake/Qt6LanguageServerPrivate/Qt6LanguageServerPrivateTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6LanguageServerPrivate/Qt6LanguageServerPrivateTargets.cmake
/usr/lib64/cmake/Qt6LanguageServerPrivate/Qt6LanguageServerPrivateVersionlessTargets.cmake
/usr/lib64/libQt6JsonRpc.prl
/usr/lib64/libQt6JsonRpc.so
/usr/lib64/libQt6LanguageServer.prl
/usr/lib64/libQt6LanguageServer.so
/usr/lib64/qt6/mkspecs/modules/qt_lib_jsonrpc_private.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_languageserver_private.pri

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libQt6JsonRpc.so.6.7.3
/V3/usr/lib64/libQt6LanguageServer.so.6.7.3
/usr/lib64/libQt6JsonRpc.so.6
/usr/lib64/libQt6JsonRpc.so.6.7.3
/usr/lib64/libQt6LanguageServer.so.6
/usr/lib64/libQt6LanguageServer.so.6.7.3
/usr/lib64/qt6/metatypes/qt6jsonrpcprivate_relwithdebinfo_metatypes.json
/usr/lib64/qt6/metatypes/qt6languageserverprivate_relwithdebinfo_metatypes.json
/usr/lib64/qt6/modules/JsonRpcPrivate.json
/usr/lib64/qt6/modules/LanguageServerPrivate.json

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qt6languageserver/7713a1753ce88f2c7e6b054ecc8e4c786df76300
/usr/share/package-licenses/qt6languageserver/79453f55fa8ee32d7b95581473edcbfd043e088f
/usr/share/package-licenses/qt6languageserver/c70af14df11e3908dfc10397b1ba4b1f346661f3
/usr/share/package-licenses/qt6languageserver/dc8f2e570bf431427dbc3bab9d4d551b53a60208
